[build]
  publish = ".next"
  command = "npm install tailwindcss postcss autoprefixer && npm run build:netlify"

[build.environment]
  NODE_ENV = "production"
  SKIP_ENV_VALIDATION = "1"
  NEXT_TELEMETRY_DISABLED = "1"